# Generated by Django 4.2.7 on 2025-09-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="semester",
            field=models.CharField(
                choices=[
                    ("first", "Premier Semestre"),
                    ("second", "Deuxième Semestre"),
                    ("summer", "Session d'Été"),
                    ("annual", "Rapport Annuel"),
                ],
                max_length=20,
            ),
        ),
    ]
