# Generated by Django 4.2.7 on 2025-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_transcript_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcript",
            name="file_size",
        ),
        migrations.AlterField(
            model_name="transcript",
            name="semester",
            field=models.CharField(
                choices=[
                    ("first", "Premier Semestre"),
                    ("second", "Deuxième Semestre"),
                    ("annual", "Rapport Annuel"),
                ],
                max_length=20,
            ),
        ),
    ]
