# Generated by Django 4.2.7 on 2025-09-05 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_schoolconfiguration_alter_school_options_and_more"),
        ("students", "0003_remove_transcript_file_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Class name (e.g., 'Grade 1', 'CP', '6ème')",
                        max_length=100,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="Class level for sorting (e.g., '1', '2', '3')",
                        max_length=50,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section within the class (e.g., 'A', 'B', 'Science', 'Arts')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the class",
                        null=True,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year this class belongs to (e.g., '2024-2025')",
                        max_length=20,
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum number of students allowed in this class",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["level", "name", "section"],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="schools.school",
            ),
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_class_l_326080_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_school__688227_idx",
        ),
        migrations.RemoveField(
            model_name="student",
            name="class_level",
        ),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
        migrations.AddField(
            model_name="student",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned class for this student",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.class",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["class_assigned"], name="students_st_class_a_e62c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "class_assigned", "is_active"],
                name="students_st_school__ed068e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("school", "name", "section", "academic_year")},
        ),
    ]
