# Generated by Django 4.2.7 on 2025-09-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "students",
            "0004_class_remove_student_students_st_class_l_326080_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="behaviorreport",
            options={
                "ordering": ["-incident_date", "-created_at"],
                "verbose_name": "Rapport de Comportement",
                "verbose_name_plural": "Rapports de Comportement",
            },
        ),
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["level", "name", "section"],
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="parentstudent",
            options={
                "verbose_name": "Relation Parent-Étudiant",
                "verbose_name_plural": "Relations Parent-Étudiant",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentrecord",
            options={
                "ordering": ["-due_date", "-created_at"],
                "verbose_name": "Enregistrement de Paiement",
                "verbose_name_plural": "Enregistrements de Paiement",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
            },
        ),
        migrations.AlterModelOptions(
            name="transcript",
            options={
                "ordering": ["-academic_year", "-semester"],
                "verbose_name": "Relevé de Notes",
                "verbose_name_plural": "Relevés de Notes",
            },
        ),
        migrations.AlterField(
            model_name="behaviorreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("positive", "Comportement Positif"),
                    ("negative", "Comportement Négatif"),
                    ("neutral", "Observation Générale"),
                    ("achievement", "Réussite"),
                    ("discipline", "Mesure Disciplinaire"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="behaviorreport",
            name="severity_level",
            field=models.CharField(
                choices=[
                    ("low", "Faible"),
                    ("medium", "Moyen"),
                    ("high", "Élevé"),
                    ("critical", "Critique"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="academic_year",
            field=models.CharField(
                help_text="Année académique de cette classe (ex: '2024-2025')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description optionnelle de la classe", null=True
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="level",
            field=models.CharField(
                help_text="Niveau de classe pour le tri (ex: '1', '2', '3')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="max_students",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Nombre maximum d'étudiants autorisés dans cette classe",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                help_text="Nom de la classe (ex: 'Grade 1', 'CP', '6ème')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="Section dans la classe (ex: 'A', 'B', 'Science', 'Arts')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parentstudent",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("father", "Père"),
                    ("mother", "Mère"),
                    ("guardian", "Tuteur"),
                    ("grandfather", "Grand-père"),
                    ("grandmother", "Grand-mère"),
                    ("uncle", "Oncle"),
                    ("aunt", "Tante"),
                    ("other", "Autre"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Espèces"),
                    ("bank_transfer", "Virement Bancaire"),
                    ("card", "Carte de Crédit/Débit"),
                    ("mobile_money", "Mobile Money"),
                    ("check", "Chèque"),
                    ("other", "Autre"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("tuition", "Frais de Scolarité"),
                    ("library", "Frais de Bibliothèque"),
                    ("laboratory", "Frais de Laboratoire"),
                    ("sports", "Frais de Sport"),
                    ("transport", "Frais de Transport"),
                    ("meal", "Frais de Repas"),
                    ("uniform", "Frais d'Uniforme"),
                    ("examination", "Frais d'Examen"),
                    ("other", "Autre"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En Attente"),
                    ("paid", "Payé"),
                    ("overdue", "En Retard"),
                    ("cancelled", "Annulé"),
                    ("refunded", "Remboursé"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                help_text="Classe assignée à cet étudiant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Masculin"),
                    ("female", "Féminin"),
                    ("other", "Autre"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                help_text="Numéro d'identification spécifique à l'école", max_length=50
            ),
        ),
    ]
