# Generated by Django 4.2.7 on 2025-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_schoolconfiguration_alter_school_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
