# Generated by Django 5.2.4 on 2025-08-19 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_schoolconfiguration_alter_school_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('firebase_path', models.CharField(max_length=500)),
                ('firebase_url', models.URLField()),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('transcript', 'Academic Transcript'), ('behavior_report', 'Behavior Report'), ('payment_receipt', 'Payment Receipt'), ('student_document', 'Student Document'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='schools.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_file_upload',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['school', 'file_type'], name='files_file__school__e2b695_idx'), models.Index(fields=['uploaded_by', 'uploaded_at'], name='files_file__uploade_666790_idx')],
            },
        ),
    ]
