# Generated by Django 5.2.5 on 2025-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_alter_fileupload_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="firebase_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="firebase_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
