# Generated by Django 5.2.5 on 2025-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sent_via_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="delivered_via_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
